########################################################################
###  This script is used to temporarily define any new primitives
###  until they are officially added to the networks by the
###  testdeck administrator/release administrator.
###
###  Sep 8 ,2010	jck   definition for getenv primitive
########################################################################

   # Define the new primitives ...

String

define:'getenv'            toBePrimitive: 387 ;
