//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VLINK.RC
//
#define IDR_MAINFRAME                   2
#define IDR_VLINKTYPE                   3
#define IDR_VLINKTYPE_SRVR_IP           4
#define IDR_VLINKTYPE_SRVR_EMB          5
#define IDR_VLINKTYPE_CNTR_IP           6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_FAILED_TO_CREATE            102
#define IDB_VLinkLogo2                  102
#define IDP_WINSOCK_INIT_FAILED         103
#define IDB_VLinkLogo1                  104
#define IDD_NetworkConnectionParameters 105
#define IDD_HiddenControlsDialog        107
#define IDI_VLink32                     108
#define IDC_WinsockNotificationWindow   1000
#define IDC_User                        1011
#define IDC_Password                    1012
#define IDC_Host                        1013
#define IDC_DataBase                    1014
#define ID_CANCEL_EDIT                  32768

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
