/*****  Machine Specific Lock Management Header File *****/
#ifndef siLOCK_H
#define siLOCK_H

/**************************************
 *****  Network Locking Services  *****
 **************************************/

/****************
 *  Invariants  *
 ****************/

PublicFnDecl int
    STDOSS_AcquireLockSet (),
    STDOSS_DiscardLockSet (),
    STDOSS_LockOp ();

/* Symbolic constants for the "lockf" function: */
#ifndef F_ULOCK
#define F_ULOCK	0	/* Unlock a previously locked region */
#define	F_LOCK	1	/* Lock a region for exclusive use */
#define	F_TLOCK	2	/* Test and lock a region for exclusive use */
#define F_TEST	3	/* Test a region for a previous lock */
#endif /* F_ULOCK */
#define F_ACCESS 10	/* Access a set of locks */

/********************
 *  Customizations  *
 ********************/

#ifdef hp9000s500		/*****  HP9000 Series 500  *****/

PublicFnDecl int
    lockf ();

typedef int
     *STDOSS_LSB, STDOSS_LockStatusBlock;

#define STDOSS_LSB_FileD(lsb)		(*(lsb))

#endif

#ifdef VMS			/*****  VAX/VMS  *****/


/*---------------------------------------------------------------------------
 * An STDOSS_LockStatusBlock is maintained to manage file locking operations.
 * The first three fields are defined to correspond to what VMS requires for
 * its internal locking routines. The last two fields are optional in that
 * regard, but necessary for the locking operations that the system performs.
 *
 *  Field Descriptions:
 *	VMScond			- A status value which is set by VMS following
 *				  calls to the system service routines.
 *	reserved		- reserved for Digital.
 *	lockId			- An number generated by VMS identifying the
 *				  lock.
 *	fileD			- A file descriptor for the file to be locked
 *	sublockArray		- An array of integers corresponding to the
 *				  sublocks of this lock set.  The first slot
 *				  in the array contains the length of the 
 *				  remainder of the array.
 *---------------------------------------------------------------------------
 */

typedef struct {
    unsigned short	VMScond,
			reserved;
    unsigned int	lockId,
			fileD,
    			*sublockArray;
} *STDOSS_LSB, STDOSS_LockStatusBlock;

#define STDOSS_LSB_VMScond(lsb)		((lsb)->VMScond)
#define STDOSS_LSB_LockId(lsb)		((lsb)->lockId)
#define STDOSS_LSB_FileD(lsb)		((lsb)->fileD)
#define STDOSS_LSB_SubLocks(lsb)	((lsb)->sublockArray)
#define STDOSS_LSB_NumSubLocks(lsb)	(*((lsb)->sublockArray))
#define STDOSS_LSB_SubLock(lsb, n)	((lsb)->sublockArray[(n) + 1])

#endif

#ifdef apollo			    /*****  DOMAIN/IX  *****/

typedef int
     *STDOSS_LSB, STDOSS_LockStatusBlock;

#define STDOSS_LSB_FileD(lsb)		(*(lsb))
#endif

#ifdef sun		/*****  Sun  *****/

PublicFnDecl int
    lockf ();

typedef int
     *STDOSS_LSB, STDOSS_LockStatusBlock;

#define STDOSS_LSB_FileD(lsb)		(*(lsb))

#endif

#endif


/************************** SOURCE FILE HISTORY: ************************/
/************************************************************************
  SIlock.h 1 replace /users/jck/system
  880330 21:55:43 jck SIutil.h

 ************************************************************************/
/************************************************************************
  SIlock.h 2 replace /users/jck/system
  880407 10:51:19 jck Cleaned Up VAX interface

 ************************************************************************/
/************************************************************************
  SIlock.h 3 replace /users/jck/system
  880421 20:00:34 jck Added lock definitions for the Apollo

 ************************************************************************/
/************************************************************************
  SIlock.h 4 replace /users/jck/system
  880526 14:44:46 jck Interfaced with the new Apollo lock server

 ************************************************************************/
/************************************************************************
  SIlock.h 5 replace /users/jck/system
  880915 12:11:21 jck Modify lock-set acquisition protocol

 ************************************************************************/
/************************************************************************
  SIlock.h 6 replace /users/m2/backend
  890927 14:29:31 m2 SUN port (preliminary)

 ************************************************************************/
