

/* Stub START:NN234906836474 */
#define VCA_PASSIVE_DISTRIBUTED_CALLBACK_HELPERS 
#define VCA_PASSIVE_DISTRIBUTED_CALLBACK_INFO (void)0
/* Stub END:NN234906836474 */

/* Stub: START:JOASE5946456699 */
#define VERIFY_EX2(exp, description) (void)0
#define VMS_LOCKING_CONTENTION_TESTING_FAILGUARD_START 
#define VMS_LOCKING_CONTENTION_TESTING_FAILGUARD_END 
#define VMS_LOCKING_CONTENTION_TESTING_UNLOCKGUARD_START 
#define VMS_LOCKING_CONTENTION_TESTING_UNLOCKGUARD_END 

/* Stub: END:JOASE5946456699 */


