#!/bin/bash

####  If git is installed, ...
if type git >& /dev/null; then
####  ... and we're inside a git work-tree, ...
    if git rev-parse --is-inside-work-tree >& /dev/null; then
	echo "git:work-tree=$(git rev-parse --show-toplevel),branch=$(git rev-parse --abbrev-ref HEAD),commit=$(git rev-parse --short HEAD)"
    fi
fi
